# Generated by Django 3.1.3 on 2020-11-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20201115_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='photo_main',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photo_main_height',
            new_name='photo_height',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photo_main_width',
            new_name='photo_width',
        ),
    ]
