# Generated by Django 3.1.3 on 2020-11-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20201115_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(blank=True, height_field='photo_height', help_text='Main Picture', null=True, upload_to='photos/', verbose_name='Main Picture', width_field='photo_width'),
        ),
    ]
