# Generated by Django 3.1.3 on 2020-11-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rep',
            name='position',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
